### ISSUE TITLE
Migrate to RTE 3.0.0

### ISSUE THREAD

**Issue by edwingamboa** [cubbles/cubx-generic-component-viewer#4]
* [x] Migrate klay-js-0.3.5 to RTE 3.0.0 (iCubbles/klayjsd3-wrapper#1)
* [x] Migrate jquery-2.1.4 to RTE 3.0.0 (iCubbles/jquery-wrapper#1)
* [x] Migrate d3-tip-0.6.7 to RTE 3.0.0 (iCubbles/d3-tip-wrapper#1)
* [x] file-saver-1.3.2 to RTE 3.0.0 (iCubbles/file-saver#1)
